---
- name: Remove files from previous installation.
  file:
    path: "{{ jenkins_dir }}"
    state: absent

- name: Create directory for compose file.
  file:
    path: "{{ src_jenkins }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yaml.
  copy:
    src: "{{ src_compose }}" 
    dest: "{{ src_jenkins }}"
    mode: '0644'

- name: Launch docker-compose.
  shell: "docker-compose -f roles/ansible_jenkins/{{ src_compose }} up -d"

- name: Wait 5 seconds for the container to start.
  pause:
    seconds: 5

- name: Print initial admin password.
  command: cat "{{ init_pass }}" 
  register: pass_out

- debug: msg="{{ pass_out.stdout }}"
